# Site settings
title: MiniWaveMe
email: admin@miniwave.me
description: blog miniwaveme
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.miniwave.me" # the base hostname & protocol for your site
twitter_username: username
github_username: username

# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]
